version: '3.0'
services:
  web:
    build:
      context: ../..
    depends_on:
      - db
    ports:
      - '8080:3000'
    env_file: .env
  db:
    image: mariadb
    env_file: .env
    ports:
      - '3306:3306'
